version: 2.1

executors:
  ruby-executor:
    docker:
      - image: ruby:3.0.0

jobs:
  build:
    # ... your existing build job

  deploy:
    executor: ruby-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to EC2
          command: |
            chmod +x deploy.sh
            ./deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build
