version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-frontend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
          working_directory: ~/tm/frontend

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: deploy-application
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf tm/; git clone https://github.com/lukeohanlon/tm.git; source tm/deploy.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-frontend:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build-frontend
