version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

  ruby-executor:
    docker:
      - image: ruby:3.0.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build and test frontend
          command: npm run build
      - persist_to_workspace:
          root: frontend
          paths:
            - build

  backend:
    executor: ruby-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec
      - persist_to_workspace:
          root: backend
          paths:
            - tmp

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - backend:
          requires:
            - build
