version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

jobs:
  build:
    working_directory: ~/tm
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5' 
          key: dependency-cache-frontend-{{ checksum "frontend/package-lock.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-frontend-{{ checksum "frontend/package-lock.json"}} 
          paths:
            - ./frontend/node_modules
      - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: deploy-application
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/MedTracker.pem $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf tm/; git clone https://github.com/lukeohanlon/tm.git; source tm/deploy.sh"
