version: 2.1

executors:
  ruby-executor:
    docker:
      - image: ruby:3.0.0

jobs:
  build:
    working_directory: ~/tm/frontend
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build and test frontend
          command: npm run build
      - persist_to_workspace:
          root: frontend
          paths:
            - build

  backend:
    executor: ruby-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec
      - persist_to_workspace:
          root: backend
          paths:
            - tmp

  deploy:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            chmod 400 MedTracker.pem
            ssh -i "MedTracker.pem" $EC2_USERNAME@$EC2_PUBLIC_DNS "cd tm && ./deploy.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - backend:
          requires:
            - build
      - deploy:
          requires:
            - backend
